minor/urls.py
from django.urls import path,include, re_path
from . import  views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'minor'

urlpatterns = [

    path('',views.HomeView.as_view(),name='new-home'),
    path('project/<int:pk>/',views.ProjectDetailView.as_view(), name= 'project'),
    path("group-registration/", views.group_registration,name='group-registration'),
    path("faculty-registration/", views.faculty_registration,name='faculty-registration'),
    path('login/', views.user_login,name='user-login'),
    path('logout/', views.user_logout,name = 'user-logout'),
    path('project-form/', views.project_form_view, name = 'project-form'),
    path('coordinator-projects/', views.coordinator_home, name = 'coordinator-home'),
    path('mentor-approval/<int:pk>/', views.mentor_approval, name= 'mentor-approval'),
    path('hod-approval/<int:pk>/', views.hod_approval, name= 'hod-approval'),
    path('project/<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project_edit'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path,include
from minor import urls
from django.conf import settings 
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(urls)),
     url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project3/urls.py
from django.contrib import admin
from django.urls import path,include
from minor import urls
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(urls)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minor/forms.py
from django import forms
from .models import FacultyInfo, GroupInfo, Project
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
CHOICES=[('Yes','Approved'),
         ('No','Not Approved')]

class UserInfoForm(forms.ModelForm):
    min_length = 8
    password = forms.CharField(widget = forms.PasswordInput(),validators=[MinLengthValidator(int(min_length))])

    class Meta:
        model = User
        fields = ['username','email','password']
        REQUIRED_FIELDS = ['username','email','password']

class FacultyInfoForm(forms.ModelForm):
    class Meta:
        model = FacultyInfo
        fields = ['name','department','contact']


class GroupInfoForm(forms.ModelForm):
    class Meta:
        model = GroupInfo

        fields = [
            'department','year','section',
            'mentor','group_name','member_1_name','member_1_enrollment',
            'member_2_name','member_2_enrollment',
            'member_3_name','member_3_enrollment','contact'
        ]
        REQUIRED_FIELDS = ['user','member_1_name','member_1_enrollment','mentor','department',
                            'year','section','group_name','contact'
        ]
        # REQUIRED_FIELDS = ['user','department','year','section','mentor','group_name',
        #                     'member_1_name','member_1_enrollment','contact']

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title','description']

class ProjectApprovalByMentorForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['is_approved_by_mentor']

class ProjectApprovalByHODForm(forms.Form):
        is_approved_by_HOD = forms.ChoiceField(label = 'Approve Project ?'  ,choices = CHOICES, widget = forms.RadioSelect)

# class DocumentForm(forms.ModelForm):
#     class Meta:
#         model = Project
#         fields = ('srs', 'synopsis','wbs')

minor/views.py
from django.shortcuts import render, get_object_or_404 ,redirect, reverse
from django.http import HttpResponse
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import FacultyInfo,GroupInfo, Project, HeadOfDepartment, ClassCoordinator
from .forms import UserInfoForm, FacultyInfoForm, GroupInfoForm, ProjectForm, ProjectApprovalByMentorForm, ProjectApprovalByHODForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
import datetime
class HomeView(LoginRequiredMixin,View):
    def get(self,*args,**kwargs):
        my_project = []
        hod = ''
        faculty = ''
        group = ''
        if FacultyInfo.objects.filter(user = self.request.user):
            faculty = FacultyInfo.objects.filter(user = self.request.user)[0]
            group = GroupInfo.objects.filter(mentor = faculty)
            for i in group:
                if Project.objects.filter(group = i):
                    project =  Project.objects.get(group = i)
                    my_project.append(project)
        if HeadOfDepartment.objects.filter(user = self.request.user):
            hod = HeadOfDepartment.objects.filter(user = self.request.user)[0]
            group = GroupInfo.objects.filter(department = hod.department)
            for i in group:
                project = Project.objects.get(group = i)
                my_project.append(project)
        if GroupInfo.objects.filter(user = self.request.user):
            group = GroupInfo.objects.get(user = self.request.user)
            if Project.objects.filter(group = group):
                project = Project.objects.filter(group = group)[0]
                my_project.append(project)

        d = dict()
        if faculty:
            d['faculty'] = faculty
        if hod:
            d['hod'] = hod
        if group:
            d['group'] = group
        d['my_project'] = my_project
        return render(self.request,'new_home.html',d)

class ProjectDetailView(LoginRequiredMixin,DetailView):
    model = Project
    hod = ''
    faculty = ''
    template_name = 'project_detail.html'
    def get_context_data(self, **kwargs):
        hod = ''
        faculty = ''
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        if HeadOfDepartment.objects.filter(user = self.request.user):
            hod = HeadOfDepartment.objects.filter(user = self.request.user)[0]
        elif FacultyInfo.objects.filter(user = self.request.user):
            faculty = FacultyInfo.objects.filter(user = self.request.user)[0]
        if faculty:
            context['faculty'] = faculty
        if hod:
            context['hod'] = hod
        # context['hod'] = self.

        return context

    def post(self,*args,**kwargs):
        hod = ''
        faculty = ''
        # context = super(ProjectDetailView, self).get_context_data(**kwargs)
        if HeadOfDepartment.objects.filter(user = self.request.user):
            hod = HeadOfDepartment.objects.filter(user = self.request.user)[0]
        elif FacultyInfo.objects.filter(user = self.request.user):
            faculty = FacultyInfo.objects.filter(user = self.request.user)[0]
        if self.request.method == 'POST':
            # context = super(ProjectDetailView, self).get_context_data(**kwargs)
            if faculty:
                print("Faculty ")
                user = faculty
                # print("Pk : ",pk)
                project_title = self.request.GET.get('title')
                title = project_title
                pk = kwargs.get('pk')
                project = Project.objects.get(pk = pk)
                mentor_feedback = self.request.POST.get('mentor_feedback')
                mentor_message = self.request.POST.get('mentor_message')
                project.mentor_feedback = mentor_feedback
                time = datetime.datetime.now()
                day = str(time.day)
                month = str(time.month)
                year = str(time.year)
                project.mentor_message += mentor_message +" \nSent on :  "+ day+"/" +month+"/"+year   + "\n\n\n"+"\n"
                project.save()
                return redirect("/")

            elif hod:
                print("HOD")
                # print("Pk : ",pk)
                user = hod
                pk = kwargs.get('pk')
                # project_title = self.request.GET.get('title')
                # project = Project.objects.get(self.pk = pk)
                # title = project_title
                project = Project.objects.get(pk =pk)
                hod_feedback = self.request.POST.get('hod_feedback')
                project.hod_feedback = hod_feedback
                project.save()
                return redirect("/")

            else:
                print("Student")
                # print("Pk : ",pk)
                user = self.request.user
                project_status = self.request.POST.get('project_status')
                # mentor_feedback = self.request.POST.get('mentor_feedback')
                # hod_feedback = self.request.POST.get('hod_feedback')
                project_title = self.request.GET.get('title')
                # group = GroupInfo.objects.get(self.pk = pk)
                # project = Project.objects.get(self.pk = pk)
                pk = kwargs.get('pk')
                project = Project.objects.get(pk = pk)
                synopsis = self.request.FILES['synopsis']
                wbs = self.request.FILES['wbs']
                srs = self.request.FILES['srs']
                project.status = project_status
                project.synopsis = synopsis
                project.srs = srs
                project.wbs = wbs
                time = datetime.datetime.now()
                day = str(time.day)
                month = str(time.month)
                year = str(time.year)
                project.group_message += self.request.POST.get('group_message') + " Sent on :  "+ day+"/" +month+"/"+year   + "\n\n\n"+"\n"
                # project.mentor_feedback = mentor_feedback
                # project.hod_feedback = hod_feedback
                project.save()

                return redirect("/")


@login_required
def mentor_approval(request,pk):
    project = Project.objects.get(pk = pk)
    print(project)
    if project:
        project.is_approved_by_mentor = True
    project.save()
    return redirect("/")

@login_required
def hod_approval(request,pk):
    project = Project.objects.get(pk = pk)
    print(project)
    if project:
        project.is_approved_by_HOD = True
    project.save()
    return redirect("/")

@login_required
def coordinator_home(request):
    faculty = FacultyInfo.objects.get(user = request.user)
    coordinator = ''
    group = ''
    if ClassCoordinator.objects.filter(faculty = faculty):
        coordinator = ClassCoordinator.objects.filter(faculty = faculty)[0]
    print(faculty, coordinator)
    if coordinator:
        if GroupInfo.objects.filter(department = faculty.department, section = coordinator.section, year = coordinator.year):
            group = GroupInfo.objects.filter(department = faculty.department, section = coordinator.section, year = coordinator.year)
    my_project = []
    if group:
        for i in group:
            project = Project.objects.filter(group = i)[0]
            my_project.append(project)
    return render(request,'coordinator.html',{'my_project':my_project})

def faculty_registration(request):
    registered = False
    if request.method == "POST":
        user_form = UserInfoForm(request.POST)
        faculty_form = FacultyInfoForm(request.POST)

        if user_form.is_valid() and faculty_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            faculty = faculty_form.save(commit = False)
            faculty.user = user
            faculty.save()
            registered = True
            return redirect("/")
        else:
            print(user_form.errors, faculty_form.errors)

    else:
        user_form = UserInfoForm()
        faculty_form = FacultyInfoForm()

    return render(request,'faculty_registration.html',{
                                'user_form':user_form,
                                'faculty_form':faculty_form,
                                'registered':registered
    })


def group_registration(request):
    registered = False
    if request.method == "POST":
        user_form = UserInfoForm(request.POST)
        group_form = GroupInfoForm(request.POST)
        # group_detail_form = GroupDetailForm(request.POST)
        if user_form.is_valid() and group_form.is_valid():




            # group_detail = group_detail_form.save()
            group = group_form.save(commit=False)
            # group.department = group.mentor.department
            # group.department = group.mentor.department
            if group.department == group.mentor.department:
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                group.user = user
                group.save()
                registered = True
                return redirect("/")
            else:
                return render(request,'error.html')
        else:
            print(user_form.errors, group_form.errors)

    else:
        user_form = UserInfoForm()
        group_form = GroupInfoForm()
        # group_detail_form = GroupDetailForm()
    return render(request,'group_registration.html',{
                                'user_form':user_form,
                                'group_form':group_form,
                                'registered':registered
    })

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')

minor/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
<style media="screen">
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,600');
/* html{
  scroll-behavior: smooth; */
/* } */
body{
   margin:0;
   font-family: 'Montserrat', sans-serif;
     scroll-behavior: smooth;
     background:#3a4660;

}


span{
  color:gray;
}
li{
  color:#feda6a;
}
</style>

  </head>
  <body>
    <nav style="color:white" style="" class="navbar navbar-expand-lg navbar-dark bg-black">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a style="color:#feda6a" class="navbar-brand" href="/"> <span style="color:#feda6a">Home</span> </a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">


      {% if user.is_authenticated %}
      <li  class="nav-item">
        <a class="nav-link " href=""><span style="color:#feda6a">Hey, <b>{{user.username}}</b> </span></a>
      </li>

      <li class="nav-item">
        <a style="color:#feda6a;" class="nav-link " href="/"><span style="color:#feda6a">My Projects</span></b> </a>
      </li>

      {% block head %}

      {% endblock %}
      {% else %}
      <li class="nav-item">
        <a style="color:#feda6a;" class="nav-link" href="/group-registration/">Register as group</a>
      </li>
      <li class="nav-item">
        <a style="color:#feda6a" class="nav-link " href="/faculty-registration/">Register as faculty</a>
      </li>

      <li class="nav-item">
        <a style="color:#feda6a" class="nav-link " href="/login/">Login</a>
      </li>
      {% endif %}
    </ul>

    {% if user.is_authenticated %}
    <ul class="navbar-nav" >
      <li class=" nav-item " style="margin-left : -150px">  <a class="nav-link  btn btn-outline-default my-2 my-sm-0 " href="/logout/"><span style="color:#feda6a"><b>Logout</b></span> </a></li>
    </ul>
    {% endif %}
  </div>
</nav>


  {% block content %}

  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

minor/templates/error.html
{% extends 'base.html' %}

{% block content %}

<script type="text/javascript">
  alert("Mentor and Group should have same department")

</script>






{% endblock %}

minor/templates/faculty_registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<style media="screen">
  input[type=number] {
  -moz-appearance: textfield;
}
</style>

<div style="color:#feda6a" class="container" align='center'>


    {% if registered %}
      <h1 style="color:#feda6a">Thank you for registering!!!!</h1>
    {% else %}
  <h1 style="color:#feda6a" style="font-size : 60px; font-weight : 600">Registration Form </h1><br>

  <form  class="form-group" method="post">
    {% csrf_token %}
    <h3 style="color:#feda6a">Registration Credentials</h3><br>
    <div class="form-row">

      <div style="color:#feda6a" class="form-group col-md-4 mb-0">
        {{user_form.username|as_crispy_field }}
      </div>
  <div style="color:#feda6a" class="form-group col-md-4 mb-0">
  {{user_form.email|as_crispy_field }}
  </div>
  <div style="color:#feda6a" class="form-group col-md-4 mb-0">
    {{user_form.password|as_crispy_field }}
  </div>
  </div>
  <hr style="background:#feda6a" >
  <h3 style="color:#feda6a">Faculty Details</h3><br>
  <div class="form-row">

    <div style="color:#feda6a" class="form-group col-md-4 mb-0">
      {{faculty_form.name|as_crispy_field }}
    </div>
  <div style="color:#feda6a" class="form-group col-md-4 mb-0">
  {{faculty_form.department|as_crispy_field }}
  </div>
  <div style="color:#feda6a" class="form-group col-md-4 mb-0">
  {{faculty_form.contact|as_crispy_field }}
  </div>
  </div>
  <hr>
    <input class="btn btn-outline-warning" type="submit" name="" value="Register">
  </form>



    {% endif %}





</div>



{% endblock %}

minor/templates/invalid_login.html
{% include 'base.html' %}

<div class="container">

  <script type="text/javascript">
      alert("Invalid Credentials!!! Please login with correct credentials...")
  </script>

</div>

minor/templates/project_detail.html
{% extends 'base.html' %}
{% block head %}
{% if not hod %}
<li class="nav-item">
   <a style="color:#feda6a" data-toggle="modal" href="#myModal" class="nav-link">Messages </a>
</li>
<div style="color:green" class="modal" id="myModal">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title">Messages</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
         </div>
         <div class="container"></div>
         <div align='center' class="modal-body">
            <a data-toggle="modal" href="#myModal2" class="btn btn-primary">Sent Messages</a>
            <a data-toggle="modal" href="#myModal3" class="btn btn-primary">Received Messages</a>
         </div>
         <div class="modal-footer">
            <a href="#" data-dismiss="modal" class="btn">Close</a>
            <a href="#" class="btn btn-primary">Save changes</a>
         </div>
      </div>
   </div>
</div>
<div style="color:green" class="modal" id="myModal2" data-backdrop="static">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title">Sent Messages</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
         </div>
         <div class="container"></div>
         <div class="modal-body">
            {% if faculty %}
            {% if project.mentor_message %}
            {{project.mentor_message|linebreaks}}
            {% else %}
            <h3>No messages!!!!</h3>
            {% endif %}
            {% else %}
            {% if project.group_message %}
            {{project.group_message|linebreaks}}
            {% else %}
            <h3>No messages!!!</h3>
            {% endif %}
            {% endif %}
         </div>
         <div class="modal-footer">
            <a href="#" data-dismiss="modal" class="btn">Close</a>
            <a href="#" class="btn btn-primary">Save changes</a>
         </div>
      </div>
   </div>
</div>
</div>
<div style="color:green" class="modal" id="myModal3" data-backdrop="static">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title">Received Messages</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
         </div>
         <div class="container"></div>
         <div class="modal-body">
            {% if faculty %}
            {% if project.group_message %}
            {{project.group_message|linebreaks}}
            {% else %}
            <h3>No messages!!!!</h3>
            {% endif %}
            {% else %}
            {% if project.mentor_message %}
            {{project.mentor_message|linebreaks}}
            {% else %}
            <h3>No messages!!!</h3>
            {% endif %}
            {% endif %}
         </div>
         <div class="modal-footer">
            <a href="#" data-dismiss="modal" class="btn">Close</a>
            <a href="#" class="btn btn-primary">Save changes</a>
         </div>
      </div>
   </div>
</div>
{% endif %}
{% endblock %}
{% block content %}
<style media="screen">
   @import url('https://fonts.googleapis.com/css?family=Montserrat:400,600');
   body{
   margin:0;
   background: ;
   font-family: 'Montserrat',sans-serif;
   }
   .blue-container{
   width: 100%;
   background: #feda6a;
   color:#3a4660;
   margin-top: 5%;
   padding-top: 2%;
   padding-bottom: 0.5%;
   border-top-left-radius: 40px;
   border-bottom-right-radius : 50px;
   }
   p,blockquote{
   font-size: 0.9em;
   line-height: 1.6em;
   font-weight: 600;
   }
   ul{
   list-style: none;
   margin: 0;
   padding: 0;
   }
   .details{
   width: 100%;
   background: rgb(30,43,46);
   color:beige;
   margin-top: 5%;
   padding-top: 2%;
   padding-bottom: 0.5%;
   border-top-left-radius: 40px;
   border-bottom-right-radius : 50px;
   }
   input, text{
   border-radius :40px;
   }
</style>
<div class="container " align='center'>
<h1 style="color: #feda6a; font-size : 5em;">Project Details</h1>
<div class="blue-container">
   <div class="container">
      <ul >

         <li>
            <h1 style="color: #3a4660; font-size : 4em;">{{project.title}}</h1>
         </li>
         <li>
            <h1 style="color: #3a4660; font-size : 24px;">Year :  {{project.group.year}} <br> Section : {{project.group.section}}</h1>
         </li>
         <li>
            <p style="color: #3a4660; font-size : 18px">{{project.description}}</p>
         </li>
      </ul>
   </div>
   </div
   <br>
   <div class="details container ">
      <ul>
         <p>Project Status : {{project.status}}</p>
         <p>Mentor Feedback : {{project.mentor_feedback}}</p>
         <p>HOD Feedback : {{project.hod_feedback}}</p>
      </ul>
   </div>
   <br><br><br>
   <!-- WBS : {{project.wbs}} -->
   {% if user.is_authenticated and faculty %}
   <!-- /      Mentor :{{project.group.mentor}} -->
   <!-- MESSAGE FROM GROUP : <b>{{project.group_message|linebreaks}}</b><br> -->
   <form class="form-group" method="post">
      {% csrf_token %}
      <p style="color: #feda6a;" > MENTOR FEEDBACK</p>
      <input   class="form-control" type="text" name="mentor_feedback" value=""><br>
      <p style="color: #feda6a;" > MENTOR MESSAGE</p>
      <div class="">
         <textarea  class="form-control"  name="mentor_message" rows="8" cols="80"></textarea><br>
      </div>
      <input  class="btn btn-outline-success" type="submit" name="" value="Submit">
   </form>
   {% if project.is_approved_by_mentor %}
   <button class="btn btn-info" type="button" value="Approved by mentor">Approved by mentor</button>
   {% else %}
   <a type="submit"  class="btn btn-outline-warning" href= "{{ project.mentor_approval }}" value="Approval by mentor">Approval by mentor</a>
   {% endif %}
   {% if project.is_approved_by_HOD %}
   <button class="btn btn-info" type="button" name="">Approved by HOD</button>
   {% else %}
   <button class="btn btn-warning" "> Project not approved by HOD</button>
   {% endif %}
   {% elif user.is_authenticated and hod %}
   <form class="form-group" method="post">
      {% csrf_token %}
      <p style="color:#feda6a">HOD FEEDBACK</p>
      <input  class="form-control" type="text" name="hod_feedback" value=""><br>
      <input  class="btn btn-outline-success" type="submit" name="" value="Submit">
   </form>
   {% if project.is_approved_by_HOD %}
   <button class="btn btn-info" type="button" name="">Approved by HOD</button>
   {% else %}
   <a type="submit" class="btn btn-outline-success" href="{{ project.hod_approval }}" value="Approval by HOD">Approval by HOD</a>
   {% endif %}
   {% else %}
   <!-- MENTOR MESSAGE :   <b>{{project.mentor_message|linebreaks}}</b> -->
   <a class="btn btn-primary" href="{% url 'minor:project_edit' pk=project.pk %}"><span class="glyphicon glyphicon-pencil">Edit Projcet</span></a>
   <form enctype="multipart/form-data" class="form-group" method="post">
      {% csrf_token %}
      <p style="color:#feda6a">WBS</p>
      <input class="form-control"  type="file" name="wbs" value=""><br>
      <p style="color:#feda6a">SYNOPSIS</p>
      <input class="form-control"  type="file" name="synopsis" value=""><br>
      <p style="color:#feda6a">SRS</p>
      <input class="form-control"  type="file" name="srs" value=""><br>
      <p style="color:#feda6a">Project Status</p>
      <input   class="form-control" type="text" name="project_status" value="" ><br>
      <p style="color:#feda6a">Message to Mentor</p>
      <textarea class="form-control" name="group_message" rows="8" cols="80"></textarea>
      <br>
      <input  class='btn btn-outline-success' type="submit" name="" value="Update Status">
   </form>
   {% if project.is_approved_by_mentor %}
   <button class="btn btn-info" type="button" value="Approved by mentor">Approved by mentor</button>
   {% else %}
   <a type="submit" style="color:#feda6a"  class="btn btn-outline-warning"  value="Approval by mentor">Not approved by Mentor</a>
   {% endif %}
   {% if project.is_approved_by_HOD %}
   <button class="btn btn-info" type="button" name="">Approved by HOD</button>
   {% else %}
   <button style="color:#feda6a" class="btn btn-outline-warning" > Project not approved by HOD</button>
   {% endif %}
   {% endif %}
   <br>
   <br>
   <a class="btn btn-success" href='{{MEDIA_URL}}{{project.wbs}}'  >Download WBS</a>
   <a class="btn btn-success" href="{{MEDIA_URL}}{{project.synopsis}}" >SYNOPSIS</a>
   <a class="btn btn-success" href="{{MEDIA_URL}}{{project.srs}}" >Download SRS</a>
   <br><br>
</div>
{% endblock %}